Helsinki_CSB22_P1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('notes.urls')),
#    path('admin/', admin.site.urls),
]

notes/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name = "notes"

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login_user, name='login'),
	path('logout/', LogoutView.as_view(next_page='/login/'), name='logout'),
    path('notes/', views.notes, name='notes'),
    path('note/', views.note, name='note'),
    path('remove/<int:id>', views.remove_note, name='remove')
]

notes/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Note(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_id')
    title = models.CharField(max_length=255)
    content = models.TextField(blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('title',)

notes/forms.py
from django import forms

class RegisterForm(forms.Form):
    username = forms.CharField(label='username', max_length=100)
    password = forms.CharField(label="password", widget=forms.PasswordInput, max_length=100)

class LoginForm(forms.Form):
    username = forms.CharField(label='username', max_length=100)
    password = forms.CharField(label="password", widget=forms.PasswordInput, max_length=100)

notes/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .forms import LoginForm, RegisterForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from .models import Note
from django.template.loader import render_to_string
import sqlite3
import datetime
from hashlib import md5

# Create your views here.
def index(request):
    if request.user.is_authenticated:
        return redirect('/notes')
    return render(request, 'index.html')


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            User.objects.create(username=username, password=password)
#            User.objects.create(username=username, password=md5(password))
            return redirect('/login')

    else:
        form = RegisterForm()
    return render(request, 'register.html', {'form': form})


def login_user(request):
    if request.user.is_authenticated:
        return redirect('/notes')
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        #don't use get, otherwise django raises an exception if no user was found
        user = User.objects.filter(username=username, password=password).first()        
#        user = User.objects.filter(username=username, password=md5(password)).first()
        if user is not None:
            login(request, user)
            return redirect('/notes')

    form = LoginForm()
    return render(request, 'login.html', {'form': form})


@login_required(redirect_field_name="/login.html")
def note(request):
    if request.method == 'GET':
        note_id = int(request.GET.get('id', 0))
        if note_id > 0:
            selected_note = Note.objects.filter(id=note_id).first()
            #if not selected_note or selected_note.user_id != request.user.id:
            #    return HttpResponse(render_to_string('error.html', {'error_message': 'Unauthorized!'}), status=401)
            return render(request, 'note.html', { 'note': selected_note })
        return render(request, 'note.html')
    
    if request.method == 'POST':
        id = request.POST.get('id', 0)
        note_id = int(0 if not id else id)
        title = request.POST.get('title')
        content = request.POST.get('content', '')
        # content = 'content", "123", "123", 1);delete from notes_note;--

        if note_id > 0:
            note = Note.objects.get(pk=note_id)
            note.title = title
            note.content = content
            note.save()

            return redirect('/note/?id=%i' % note_id)
        else:
            conn = sqlite3.connect('./db.sqlite3')
            cursor = conn.cursor()
            dt_now = datetime.datetime.now()
            query = 'INSERT INTO notes_note (title, content, created_at, modified_at, user_id) values("%s","%s","%s","%s","%s")'\
                % (title, content, dt_now, dt_now, request.user.id)
            cursor.executescript(query)
            conn.commit()
            return redirect('/note/?id=%i' % Note.objects.latest('id').id)
#            note = Note.objects.create(title=title, content=content, user_id=request.user.id)
#            return redirect('/note/?id=%i' % note.id)
    return render(request, 'notes.html')


@login_required(redirect_field_name="/login.html")
def notes(request):
    notes = Note.objects.filter(user_id=request.user.id)
    context = {
        'notes': notes,
    }
    return render(request, 'notes.html', context)


@login_required(redirect_field_name="/login.html")
def remove_note(request, id):
    note = Note.objects.filter(id=id)
    if not note:
#    if not note or note.user_id != request.user:
        return HttpResponse(render_to_string('error.html', {'error_message': 'Unauthorized!'}), status=401)
    note.delete()
    return redirect('/notes')

notes/templates/error.html
<!DOCTYPE html>
<html>
    {% include "head.html" %} 
    <body>
        {% include "menu.html" %}    
        <div style="height: 90vh; width: 100%; display: flex; align-items: center; justify-content: center;">
            <h1 style="font-size: 50px;">{{ error_message }}</h1>
        </div>
    </body>
</html>

notes/templates/head.html
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Notes</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
</head>

notes/templates/index.html
<!DOCTYPE html>
<html>
    {% include "head.html" %}    
    <body>
        <h3>Please login to add the notes</h3>
        <a href="{% url 'notes:login' %}"> login </a>
        <br />
        <a href="{% url 'notes:register' %}"> register </a>
    </body>
</html>

notes/templates/login.html
<!DOCTYPE html>
<html>
    {% include "head.html" %}    
    <body>
      <h2>Login</h2>
      <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
      </form>
      
      <a href="{% url 'notes:register' %}">register</a>
    </body>
</html>

notes/templates/menu.html
<nav class="navbar is-dark">
    <div class="navbar-brand">
        <a href="{% url 'notes:note' %}" class="navbar-item">Add note</a>
    </div>

    <div class="navbar-brand">
        <a href="{% url 'notes:notes' %}" class="navbar-item">All notes</a>
    </div>

    <div class="navbar-menu">
        <div class="navbar-end">
            <a href="{% url 'notes:logout' %}" class="navbar-item">Logout</a>
        </div>
    </div>
</nav>

notes/templates/note.html
<!DOCTYPE html>
<html>
    {% include "head.html" %}    
    <body>
        {% include "menu.html" %}    

        <form method="post" action="{% url 'notes:note' %}">
            {% csrf_token %}

            <input type="hidden" name="id" value="{{ note.id }}">

            <div class="field">
                <label class="label">
                    Title
                    {% if note %}
                        <span class="has-text-grey-light">
                            Created at: {{ note.created_at|date:"m/d Y" }} / 
                            Modified at: {{ note.modified_at|date:"m/d Y" }}
                        </span>
                    {% endif %}
                </label>

                <div class="control">
                    <input type="text" class="input" name="title" placeholder="Title"{% if note %} value="{{ note.title }}"{% endif %}>
                </div>
            </div>

            <div class="field">
                <label class="label">Content</label>

                <div class="control">
                    <textarea class="textarea" name="content" placeholder="Content">{% if note %}{{ note.content }}{% endif %}</textarea>
                </div>
            </div>

            <div class="field is-grouped">
                <div class="control">
                    <button class="button is-primary">Save</button>
                </div>
                {% if note %}
                    <div class="control">
                        <a href="{% url 'notes:remove' note.id %}" class="button is-danger">Delete</a>
                    </div>
                {% endif %}
            </div>
        </form>
    </body>
</html>

notes/templates/notes.html
<!DOCTYPE html>
<html>
    {% include "head.html" %} 
    <body>
        {% include "menu.html" %}    

        <p class="menu-label">Notes</p>

        <ul class="menu-list">
            {% for note in notes %}
            <div style="position: relative; height: 50px;">
                <li>
                    <a href="{% url 'notes:note' %}?id={{ note.id }}">{{ note.title|safe }}</a>
                    <!--<a href="{% url 'notes:note' %}?id={{ note.id }}">{{ note.title }}</a> -->
                </li>
                <div class="control" style="position: absolute; right: 0; top: 0;">
                    <a href="{% url 'notes:remove' note.id %}" class="button is-danger">Delete</a>
                </div>
            </div>
            {% endfor %}
        </ul>
    </body>
</html>

notes/templates/register.html
<!DOCTYPE html>
<html>
    {% include "head.html" %}    
    <body>
        {% block title %}Create an Account{% endblock %}

        {% block content %}
            <form action="{% url 'notes:register' %}" method="POST" class="form-group">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Register</button>
            </form>
        {% endblock %} 
        
        <a href="{% url 'notes:login' %}">Already registered</a>
    </body>
</html>